# Homework 1

[Main Repo](https://github.com/DataTalksClub/machine-learning-zoomcamp/tree/master)

[Homework 1](https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2023/01-intro/homework.md)

### 1. Which versions of pandas?

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3


In [2]:
import polars as pl

print(pl.__version__)



0.19.3


### 2. Ingest dataset & Inspect

In [3]:
## PANDAS

CSV_DATA_PATH = "./housing.csv"

df = pd.read_csv(CSV_DATA_PATH)

columns = df.columns

print(len(columns), " COLUMNS: ", columns)

10  COLUMNS:  Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')


In [4]:
### POLARS

pl_df = pl.read_csv(CSV_DATA_PATH)

pl_columns = pl_df.columns

print(len(pl_columns), " COLUMNS: ", pl_columns)

10  COLUMNS:  ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']


### 3. Missing data?

In [5]:
### PANDAS

missing_columns_df = df.columns[df.isnull().any()].tolist()
print(missing_columns_df)


['total_bedrooms']


In [6]:
### POLARS

missing_columns_pl = [col for col in pl_df.columns if pl_df.filter(pl_df[col].is_null()).height > 0]
print(missing_columns_pl)


['total_bedrooms']


### 4. Unique Values

In [7]:
### PANDAS

unique_values = df['ocean_proximity'].nunique()
print(unique_values)


5


In [8]:
### POLARS

unique_values_pl = pl_df.group_by('ocean_proximity').agg(pl.count('ocean_proximity').alias('count')).shape[0]
print(unique_values_pl)


5


### 5.  Filtering

In [11]:
### PANDAS

avg_value = df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

print(avg_value)

259212.31179039303


In [12]:
### POLARS



### 6. Imputing Missing Values

In [15]:
# 1. Calculate the average of total_bedrooms column in the dataset.
mean_before = df['total_bedrooms'].mean()
print(f"Average before filling NA: {mean_before}")

# 2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df['total_bedrooms'].fillna(mean_before, inplace=True)

# 3. Now, calculate the average of total_bedrooms again.
mean_after = df['total_bedrooms'].mean()
print(f"Average after filling NA: {mean_after}")

# 4. Has it changed?
print("Has the average changed?", mean_before != mean_after)


Average before filling NA: 537.8705525375617
Average after filling NA: 537.8705525375617
Has the average changed? False


### 7. Training a Linear Regression Model


In [33]:
import numpy as np

#     Select all the options located on islands.

df_islands = df[df['ocean_proximity'] == 'ISLAND']

#     Select only columns housing_median_age, total_rooms, total_bedrooms.

selected_data = df_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']]

#     Get the underlying NumPy array. Let's call it X.

X = selected_data.values

print(X)

#     Compute matrix-matrix multiplication between the transpose of X and X. 
#     To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T.dot(X)

print(XTX)

#     Compute the inverse of XTX.

XTX_inv = np.linalg.inv(XTX)


#     Create an array y with values [950, 1300, 800, 1000, 1300].

y = np.array([950, 1300, 800, 1000, 1300])


#     Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inv.dot(X.T).dot(y)

#     What's the value of the last element of w?

print(w[-1])

[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
[[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]
5.699229455065586


## PART II: Exploratory Data Analysis

https://pandas.pydata.org/docs/user_guide

In [16]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [24]:
print(df['ocean_proximity'].unique())

print(df['ocean_proximity'].nunique())

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']
5
